UPLOAD_FOLDER = "static/logos"
SQLALCHEMY_DATABASE_URL = "mysql://app:companyday@macascript.com/companyday"
SECRET_KEY = 'clavedeprueba'
MAIL_USERNAME='carthonuni@gmail.com'
MAIL_PASSWORD='gbprmaxqawxsnlga'
MAIL_SUBJECT_PREFIX=''
MAIL_PORT=587
MAIL_SERVER='smtp.googlemail.com'
MAIL_SENDER='Josefino Perez'