"""Initial migration

Revision ID: 3a33ce6e80f1
Revises: 
Create Date: 2022-04-24 20:57:22.587925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a33ce6e80f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('is_created', sa.Boolean(), nullable=True))
    op.add_column('empresa', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('empresa', sa.Column('is_updated', sa.Boolean(), nullable=True))
    op.drop_column('empresa', 'es_actualizado')
    op.drop_column('empresa', 'es_creado')
    op.drop_column('empresa', 'es_verificado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('es_verificado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('empresa', sa.Column('es_creado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('empresa', sa.Column('es_actualizado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('empresa', 'is_updated')
    op.drop_column('empresa', 'is_active')
    op.drop_column('empresa', 'is_created')
    # ### end Alembic commands ###
