"""Updated password length

Revision ID: 49c7948f0962
Revises: a557e2560c36
Create Date: 2022-05-08 21:29:44.265217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49c7948f0962'
down_revision = 'a557e2560c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('password', sa.String(length=50), nullable=True))
    op.drop_column('empresa', 'contrasenya')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('contrasenya', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('empresa', 'password')
    # ### end Alembic commands ###
