"""UserHash y JobTeaser

Revision ID: a557e2560c36
Revises: f11f673af54d
Create Date: 2022-04-26 12:30:17.502018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a557e2560c36'
down_revision = 'f11f673af54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('esta_confirmado', sa.Boolean(), nullable=True))
    op.add_column('empresa', sa.Column('esta_creado_jb', sa.Boolean(), nullable=True))
    op.add_column('empresa', sa.Column('esta_actualizado_jb', sa.Boolean(), nullable=True))
    op.add_column('empresa', sa.Column('user_hash', sa.String(length=50), nullable=True))
    op.drop_column('empresa', 'is_confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('is_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('empresa', 'user_hash')
    op.drop_column('empresa', 'esta_actualizado_jb')
    op.drop_column('empresa', 'esta_creado_jb')
    op.drop_column('empresa', 'esta_confirmado')
    # ### end Alembic commands ###
