"""booleano para verificar por correo

Revision ID: ad807b2a886f
Revises: 708a99b4c096
Create Date: 2022-05-08 21:49:29.619702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad807b2a886f'
down_revision = '708a99b4c096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('esta_verificado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'esta_verificado')
    # ### end Alembic commands ###
