"""user_type admin: 1, company: 2

Revision ID: d2f25e4d536a
Revises: ad807b2a886f
Create Date: 2022-05-08 22:42:09.028666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f25e4d536a'
down_revision = 'ad807b2a886f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('user_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'user_type')
    # ### end Alembic commands ###
